spring:
  application:
    name: TaskService
  datasource:
    url: jdbc:postgresql://localhost:5433/task?currentSchema=task
    username: task_user
    password: task_password
    hikari:
      schema: task
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
server:
  port: 8010